### ISSUE TITLE
Update LayerSwitcher in web map builder

### ISSUE THREAD

**Issue by walkermatt** [boundlessgeo/suite#1000]
Hi, I think the web map builder uses a layer switcher based on https://github.com/walkermatt/ol3-layerswitcher. One issue that's came up a couple of times is the fact that scrolling of the list didn't work on touch devices as described in [this issue](https://github.com/walkermatt/ol3-layerswitcher/issues/18). It's now fixed so you might want to consider updating the web map builder.

**Comment by bartvde** [comment]
Hey @walkermatt thanks for the feedback, we are not using it anymore in more recent versions of WAB, but thanks for pointing us to the fix anyway.
