### ISSUE TITLE
QGIS OpenGeo Explorer plugin hides GeoServer Icons (OS X only)

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#834]
Not a bug per se, but a bit of a usability issue. When testing QGIS/Geoserver integration on OS X, the size of the QGIS menu bar (After installing the OpenGeo Explorer plugin) hides the GeoServer and PostGIS menu icons used by suite, meaning that you have to switch away from QGIS if you want to open geoserver etc.

OS X 10.10, QGIS 2.6.1

![no_icons](https://cloud.githubusercontent.com/assets/9271497/5745940/0cc90346-9be1-11e4-8635-ddfb3e1cbe8f.png)
![icons](https://cloud.githubusercontent.com/assets/9271497/5745941/0cc950e4-9be1-11e4-9503-54369ac3af05.png)

**Comment by mweisman** [comment]
This is an OS issue. Nothing we can do except tell our users to buy higher res screens
