### ISSUE TITLE
QGIS OpenGeo Explorer: GeoServer catalogs are not saved between sessions

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#836]
Restarting QGIS removes all defined geoserver catalogs.
(However, PostGIS connections are retained)

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by dakcarto** [comment]
There is a setting for the plugin, "Keep a list of previous catalog connections," under GeoServer. It is OFF by default. Maybe this should be ON instead.

**Comment by tbarsballe** [comment]
From a consistency perspective, I feel if PostGIS connections are retained by default, GeoServer connections should also be retained. Alternatively, if GeoServer conections are not retained by default, then PostGIS contections shourld not be retained either.

**Comment by dakcarto** [comment]
I think the former: "GeoServer connections should also be retained" (by default).

@volaya Is there some other reason why this setting is OFF by default?

**Comment by volaya** [comment]
Not really, it can be enabled by default

I have just changed it and now the config parameter is true by default
