### ISSUE TITLE
QGIS OpenGeo Explorer: Old error messages show up after creating geoserver workspace

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#838]
When creating a new workspace, if you had any previous error messages, they will show up again shortly after the success message appears (this is rather misleading)

For example, if you run into an error creating a workspace the error message pops up, and eventually dissapears. If you then latter succed in creating a workspace, you will get a success message, and then your error from before will show up again.

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by volaya** [comment]
Fixed in https://github.com/boundlessgeo/suite-qgis-plugin/commit/9f9ba45b5b3bee127bf262dacc0133d35b56e103
