### ISSUE TITLE
QGIS OpenGeo Explorer: Cannot publish a QGIS group to geoserver

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#840]
"Error code (500) from GeoServer: :Layer group must not be empty" when trying to drag a (nonempty) QGIS group to Geoserver groups. Same error using the "Publish" item.

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by volaya** [comment]
Not able to reproduce. Can you provide more details about the layers and the group? Maybe there is an issue uploading the layers before the group is created. Have you tried uploading the layers independently and it works fine?

**Comment by tbarsballe** [comment]
Here is the full stack trace:
Error code (500) from GeoServer: :Layer group must not be empty Traceback (most recent call last): File "/Users/tbarsballe/.qgis2/python/plugins/opengeo/gui/explorer.py", line 109, in run command(*params) File "/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/gsconfig-0.6.9-py2.7.egg/geoserver/catalog.py", line 216, in save (headers['status'], body)) FailedRequestError: Error code (500) from GeoServer: :Layer group must not be empty 

I am not able to publish Layers to geoserver from QGIS (see #839). Layers do not properly show up in the QGIS section of OpenGeo Explorer, and if I try to publish a layer (Which has a name, and shows up properly in QGIS) to geoserver from here, I get:

An error has occured while executing Python code:


Traceback (most recent call last):
  File "/Users/tbarsballe/.qgis2/python/plugins/opengeo/gui/qgsexploreritems.py", line 114, in 
    publishLayerAction.triggered.connect(lambda: self.publishLayer(tree, explorer))
  File "/Users/tbarsballe/.qgis2/python/plugins/opengeo/gui/qgsexploreritems.py", line 280, in publishLayer
    "Publish layer '" + self.element.name() + "'",
AttributeError: 'NoneType' object has no attribute 'name'


Python version:
2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]


QGIS version:
2.6.1-Brighton Brighton, 4b08b89

Python path: ['/Users/tbarsballe/Downloads/QGIS.app/Contents/MacOS/../Resources/python/plugins/processing', '/Users/tbarsballe/Downloads/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/tbarsballe/.qgis2/python', u'/Users/tbarsballe/.qgis2/python/plugins', '/Users/tbarsballe/Downloads/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/SQLite3.framework/Versions/B/Python/2.7', '/Library/Frameworks/GEOS.framework/Versions/3/Python/2.7', '/Library/Python/2.7/site-packages/numpy-override', '/Library/Frameworks/GDAL.framework/Versions/1.11/Python/2.7/site-packages', '/Library/Python/2.7/site-packages/JSTools-0.6-py2.7.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/requests-2.0.1-py2.7.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/nose_html-1.1-py2.7.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/gsconfig-0.6.9-py2.7.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/gsimporter-0.1-py2.7.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/python_dateutil-2.2-py2.7.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/six-1.7.3-py2.7.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/lxml-3.3.5-py2.7-win32.egg', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs/httplib2-0.9-py2.7.egg', '/Library/Python/2.7/site-packages/Sphinx-1.3b1-py2.7.egg', '/Library/Python/2.7/site-packages/Babel-1.3-py2.7.egg', '/Library/Python/2.7/site-packages/snowballstemmer-1.2.0-py2.7.egg', '/Library/Python/2.7/site-packages/docutils-0.12-py2.7.egg', '/Library/Python/2.7/site-packages/Pygments-2.0rc1-py2.7.egg', '/Library/Python/2.7/site-packages/Jinja2-2.7.3-py2.7.egg', '/Library/Python/2.7/site-packages/six-1.8.0-py2.7.egg', '/Library/Python/2.7/site-packages/MarkupSafe-0.23-py2.7-macosx-10.9-intel.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages', '/Users/tbarsballe/.qgis2/python/plugins/opengeo/ext-libs', '/Users/tbarsballe/Downloads/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '/Users/tbarsballe/Desktop']

**Comment by tbarsballe** [comment]
This issue was moved to boundlessgeo/suite-qgis-plugin#159
