### ISSUE TITLE
QGIS OpenGeo Explorer: Selecting multiple items has no effect

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#841]
From the QGIS section, selecting several layers and choosing ""Publish to Geoserver"" only publishes the last layer. Same with delete, etc.

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by volaya** [comment]
I just tried the following:

open 2 layers in qgis
select them and choose "publish to Geoserver"
Select the uploaded layers in the "layers" entry of the geoserver item and choose "delete"

It worked as expected

I tried in a Win machine. Might be an OSX issue, so i will try in and OSX box later.

**Comment by tbarsballe** [comment]
I'm prettey sure it is an OS X only issue, since Travis was testing on windows and didn't mention running into this.

**Comment by tbarsballe** [comment]
This issue was moved to boundlessgeo/suite-qgis-plugin#160
