### ISSUE TITLE
QGIS OpenGeo Explorer: Setting the default workspace does not update UI

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#848]
After setting a geoserver workspace as the default, the actions menu does not update (You are still able to set as default workspace)

![default](https://cloud.githubusercontent.com/assets/9271497/5747037/a1f42358-9be9-11e4-8d03-82fb65b6d589.png)

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by dakcarto** [comment]
Fixed in noted commit above (tested on Mac 10.9.5 with QGIS 2.6.1). Please close issue if you have verified the fix.

**Comment by tbarsballe** [comment]
This issue was moved to boundlessgeo/suite-qgis-plugin#163
