### ISSUE TITLE
QGIS Graphical Modeler: Changes do not take effect until you exit the modeler

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#851]
Changes to a model using the graphical modeler do not take effect unless you exit the modeler, even if the model is saved.

(Tested on OS X 10.10, QGIS 2.6.1)

**Comment by volaya** [comment]
IF running the model from within the modeler dialog, the changes are taken into account (even if not saved). 

IF running from the toolbox, the model is not changed until the dialog is closed, as you say. The dialog, however, should be modal and block interaction with the rest of QGIS (not just for this, but for other reasons as well). When opened from the regular menu, it was not being shown as modal. This commit fixes that

https://github.com/qgis/QGIS/commit/49cf93dafb0d52d46f8f84a7c2dfa9ca927a4d33
