### ISSUE TITLE
Latest QGIS packages missing psycopg2 and osgeo [python-gdal]

### ISSUE THREAD

**Issue by tbarsballe** [boundlessgeo/suite#856]
I ran into this earlier, and thought it was an issue with locally building the OpenGeo Explorer plugin, but I have independantly verified this on a clean VM, and it appears to be a packaging problem. This was working fine on the first build I tested.
From a fresh QGIS install, starting QGIS for the first time, I get the following errors:

Unable to load GdalTools plugin. The required "osgeo [python-gdal]" module is missing
Couldn't load plugin opengeo due to an error when calling its classFactory() method ... No module named psycopg2.extensions
Couldn't load plugin 'processing' ... No module named osgeo

**Comment by mweisman** [comment]
Fixed in latest OS X builds.
