### ISSUE TITLE
can not get OpenGeoSuite geoserver/webapp/composer' failed

### ISSUE THREAD

**Issue by polzader** [boundlessgeo/suite#947]
Hi
Steps
1 - git clone git://github.com/opengeo/suite.git suite
2 -  cd suite
3 - git submodule update --init --recursive
.....
Clonar en «geoserver/webapp/composer»...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:boundlessgeo/composer.git' into submodule path 'geoserver/webapp/composer' failed

Thanks

**Comment by bartvde** [comment]
Composer is a private repository not available to the general public, only our OpenGeo Suite Enterprise customers.
