### ISSUE TITLE
Geoexplorer build fails with "Unable to parse command line options: Unrecognized option: -nsu"

### ISSUE THREAD

**Issue by capooti** [boundlessgeo/suite#991]
I am trying to build GeoExplorer following these instructions:
https://github.com/boundlessgeo/suite/tree/master/geoexplorer

and I am getting this error:

$ ant build
Buildfile: /home/vagrant/git/github/boundless/suite/geoexplorer/build.xml

init-time:

init-target:

init-git:

init-buildinfo:

init-ant:

init:

build:

init-mvn:

mvn:
     [echo] mvn -nsu    install
     [exec] 
     [exec] usage: mvn [options] [<goal(s)>] [<phase(s)>]
     [exec] 
     [exec] Options:
     [exec]  -am,--also-make                        If project list is specified, also
     [exec]                                         build projects required by the
     [exec]                                         list
     [exec]  -amd,--also-make-dependents            If project list is specified, also
     [exec]                                         build projects that depend on
     [exec]                                         projects on the list
     [exec]  -B,--batch-mode                        Run in non-interactive (batch)
     [exec]                                         mode
     [exec]  -C,--strict-checksums                  Fail the build if checksums don't
     [exec]                                         match
     [exec]  -c,--lax-checksums                     Warn if checksums don't match
     [exec]  -cpu,--check-plugin-updates            Force upToDate check for any
     [exec]                                         relevant registered plugins
     [exec]  -D,--define <arg>                      Define a system property
     [exec]  -e,--errors                            Produce execution error messages
     [exec]  -emp,--encrypt-master-password <arg>   Encrypt master security password
     [exec]  -ep,--encrypt-password <arg>           Encrypt server password
     [exec]  -f,--file                              Force the use of an alternate POM
     [exec]                                         file.
     [exec]  -fae,--fail-at-end                     Only fail the build afterwards;
     [exec]                                         allow all non-impacted builds to
     [exec]                                         continue
     [exec]  -ff,--fail-fast                        Stop at first failure in
     [exec]                                         reactorized builds
     [exec]  -fn,--fail-never                       NEVER fail the build, regardless
     [exec]                                         of project result
     [exec]  -gs,--global-settings <arg>            Alternate path for the global
     [exec]                                         settings file
     [exec]  -h,--help                              Display help information
     [exec]  -N,--non-recursive                     Do not recurse into sub-projects
     [exec]  -npr,--no-plugin-registry              Don't use
     [exec]                                         ~/.m2/plugin-registry.xml for
     [exec]                                         plugin versions
     [exec]  -npu,--no-plugin-updates               Suppress upToDate check for any
     [exec]                                         relevant registered plugins
     [exec]  -o,--offline                           Work offline
     [exec]  -P,--activate-profiles <arg>           Comma-delimited list of profiles
     [exec]                                         to activate
     [exec]  -pl,--projects <arg>                   Build specified reactor projects
     [exec]                                         instead of all projects
     [exec]  -q,--quiet                             Quiet output - only show errors
     [exec]  -r,--reactor                           Dynamically build reactor from
     [exec]                                         subdirectories
     [exec]  -rf,--resume-from <arg>                Resume reactor from specified
     [exec]                                         project
     [exec]  -s,--settings <arg>                    Alternate path for the user
     [exec]                                         settings file
     [exec]  -U,--update-snapshots                  Forces a check for updated
     [exec]                                         releases and snapshots on remote
     [exec]                                         repositories
     [exec]  -up,--update-plugins                   Synonym for cpu
     [exec]  -V,--show-version                      Display version information
     [exec]                                         WITHOUT stopping build
     [exec]  -v,--version                           Display version information
     [exec]  -X,--debug                             Produce execution debug output
     [exec] Unable to parse command line options: Unrecognized option: -nsu

BUILD FAILED
/home/vagrant/git/github/boundless/suite/geoexplorer/build.xml:17: The following error occurred while executing this line:
/home/vagrant/git/github/boundless/suite/build/common.xml:279: exec returned: 1

Total time: 0 seconds

I tried to build with ant 1.8.4 and 1.9.3 and I am getting the same error.

**Comment by EASC** [comment]
have you tried installing a new version of Maven? 
maven 3.x.x
